### ISSUE TITLE
idea to avoid branching on startup

### ISSUE THREAD

**Issue by epogrebnyak** [dinosaurtirex/cmd-chat#1]
https://github.com/dinosaurtirex/cmd-chat/blob/2b2ec449992a91e4d7d3e81cad31768ea7425808/cmd_chat/__init__.py#L30-L50

You can make two entry points for your program to avoid branching in `run()` 

```
cmd-chat-server --ip ... --port ...
cmd-chat-client --ip ... --port ... --username ...
```

or maybe

```
cmd-chat serve IP_ADDRESS
cmd-chat connect IP_ADDRESS USERNAME
```

The command line interface can be `docopt` or `click`, with `click` you later move to terminal interface (TUI) via `textual`.

**Comment by dinosaurtirex** [comment]
Finally done in https://github.com/dinosaurtirex/cmd-chat/commit/e83f9e5368dd6c656f102faa2c5c1371bff79caa

**Comment by epogrebnyak** [comment]
Did send a link in about entry point in a reddit discussion, maybe you can open a separate issue on entry points and I can help with establishing it.

**Comment by dinosaurtirex** [comment]
> Did send a link in about entry point in a reddit discussion, maybe you can open a separate issue on entry points and I can help with establishing it.

Got it! Thanks. I will try to do so

**Comment by dinosaurtirex** [comment]
> Did send a link in about entry point in a reddit discussion, maybe you can open a separate issue on entry points and I can help with establishing it.

So i made it but got some weird sanic issue. I'll try to rewrite backend to flask and i hope today project will be updated

**Comment by dinosaurtirex** [comment]
So i actually did it. https://github.com/dinosaurtirex/cmd-chat/commit/f24fc491d4e635336c388b318805901e58a240a1

**Comment by epogrebnyak** [comment]
Sorry didn't not mean to break your backend. Entry point seems very cool now!

**Comment by dinosaurtirex** [comment]
> Sorry didn't not mean to break your backend. Entry point seems very cool now!

Ahahhah, not, it's not up to you. it's only because sanic has been updated and included some weird start logic.
