### ISSUE TITLE
why need eval?

### ISSUE THREAD

**Issue by epogrebnyak** [dinosaurtirex/cmd-chat#2]
https://github.com/dinosaurtirex/cmd-chat/blob/2b2ec449992a91e4d7d3e81cad31768ea7425808/cmd_chat/client/client.py#L118

**Comment by dinosaurtirex** [comment]
To convert data into dictionary like object. I'll fix this. It is vulnerability, thank you

**Comment by dinosaurtirex** [comment]
Fixed in https://github.com/dinosaurtirex/cmd-chat/commit/2a8aa7a00692feb4d4d2565efd66350bd1b80539
